use_frameworks!

target 'EasyResponder_Example' do
  pod 'EasyResponder', :path => '../'

  target 'EasyResponder_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
